<script type="text/javascript">
//<![CDATA[
    
    function paylineTrySkipPaymentMethod() {
        if (!paylinePaymentSavedTransport) {
            return;
        }
        var paylinePaymentInputNames = [];
        var paylineIsUniquePaymentChoice = true;
        // retrive all radio groups
        $$('#opc-payment input[type=radio]').each(function (radio) {
            if (paylinePaymentInputNames.indexOf(radio.name)==-1)
                paylinePaymentInputNames.push(radio.name);
            else
                paylineIsUniquePaymentChoice = false;
        });
        
        // if only one input by group
        if (paylineIsUniquePaymentChoice) {
            // check all boxes
            paylinePaymentInputNames.each(function (name) {
                $$('#opc-payment input[name="' + name + '"]').first().checked = true;
            });
            // go to review step
            checkout.setStepResponse(paylinePaymentSavedTransport);
        }
    }
    
//]]>
</script>
